default:
  image: 
    name: pandoc/latex
    entrypoint: [""]
  before_script:
    - echo "install dependencies"
    - apt-get update
    - apt-get install pandoc-citeproc 
    - apt-get install lmodern 
    - apt-get install msttcorefonts 

stages:
  - build

build:
  stage: build
  script:
    - >
      pandoc ./source/02_einleitung.md
      -o dokumntation.pdf
  artifacts:
    paths:
      - dokumntation.pdf
  only:
    - main
