default:
  image: 
    name: pandoc/latex:latest-ubuntu
    entrypoint: [""]
  before_script:
    - echo "install dependencies"
    - apt-get update
    - apt-get -y install pandoc-citeproc 
    - apt-get -y install lmodern 
    - apt-get -y install fonts-liberation
    #- apt-get -y install msttcorefonts 

stages:
  - build

build:
  stage: build
  script:
    - >
      pandoc ./source/*.md
      -o dokumntation.pdf
      --pdf-engine=xelatex
  artifacts:
    paths:
      - dokumntation.pdf
  only:
    - main
