image: pandoc/latex

stages:
  - build

build:
  stage: build
  before_script:
    - apt-get update
    - apt-get install pandoc-citeproc 
    - apt-get install lmodern 
    - apt-get install msttcorefonts 

  script:
    - >
      pandoc ./source/02_einleitung.md
      -o dokumntation.pdf
  artifacts:
    paths:
      - dokumntation.pdf
  only:
    - main
